### ISSUE TITLE
Версия 2.3.0rc9 сваливается в traceback

### ISSUE THREAD

**Issue by iliadmitriev** [salute-developers/smart_app_framework#144]
```python
Traceback (most recent call last):
  File "/Users/19796006/Projects/fbapp_build/venv/lib/python3.11/site-packages/core/utils/exception_handlers.py", line 15, in _wrapper
    result = await funct(obj, *args, **kwarg)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/19796006/Projects/fbapp_build/venv/lib/python3.11/site-packages/smart_kit/models/smartapp_model.py", line 82, in answer
    commands = await handler.run(message.payload, user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/19796006/Projects/fbapp_build/venv/lib/python3.11/site-packages/smart_kit/handlers/handler_text.py", line 35, in run
    commands.extend(await self._handle_base(text_preprocessing_result, user))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/19796006/Projects/fbapp_build/venv/lib/python3.11/site-packages/smart_kit/handlers/handler_text.py", line 39, in _handle_base
    answer, is_answer_found = await self.dialogue_manager.run(text_preprocessing_result, user)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/19796006/Projects/fbapp_build/venv/lib/python3.11/site-packages/smart_kit/models/dialogue_manager.py", line 49, in run
    return await self.run_scenario(scenario_key, text_preprocessing_result, user), True
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/19796006/Projects/fbapp_build/venv/lib/python3.11/site-packages/smart_kit/models/dialogue_manager.py", line 59, in run_scenario
    run_scenario_result = await scenario.run(text_preprocessing_result, user)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/19796006/Projects/fbapp_build/venv/lib/python3.11/site-packages/scenarios/scenario_descriptions/tree_scenario/tree_scenario.py", line 173, in run
    _command = await self.get_reply(user, text_preprocessing_result, current_node.actions, field, main_form)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/19796006/Projects/fbapp_build/venv/lib/python3.11/site-packages/scenarios/scenario_descriptions/form_filling_scenario.py", line 173, in get_reply
    action_messages = await self.get_action_results(user, text_preprocessing_result, actions, action_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/19796006/Projects/fbapp_build/venv/lib/python3.11/site-packages/core/basic_models/scenarios/base_scenario.py", line 87, in get_action_results
    result = await action.run(user, text_preprocessing_result, params) or []
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/19796006/Projects/fbapp_build/venv/lib/python3.11/site-packages/core/basic_models/actions/basic_actions.py", line 150, in run
    commands.extend(await item.internal_item.run(user, text_preprocessing_result, params) or [])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object list can't be used in 'await' expression
```

**Comment by iliadmitriev** [comment]
проблема в некоторых самописных action,
в которых метод `run` не переведен на `async def run()`
