### ISSUE TITLE
ZeroDivisionError при настройке max_concurrent_messages: 1

### ISSUE THREAD

**Issue by hawtbjord** [salute-developers/smart_app_framework#98]
При выставлении max_concurrent_messages: 1 в static/template_config.yml, после старта навыка и отправки сообщения в кафку, при получении навыком сообщения эксепшн:

Traceback (most recent call last):
  File "/Users/20002185/PycharmProjects/brokeragevirtassistantportfolio/manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/20002185/.conda/envs/brokeragevirtassistantportfolio/lib/python3.9/site-packages/smart_kit/management/app_manager.py", line 96, in execute_from_command_line
    return manager.execute_from_command_line(argv)
  File "/Users/20002185/.conda/envs/brokeragevirtassistantportfolio/lib/python3.9/site-packages/smart_kit/management/app_manager.py", line 80, in execute_from_command_line
    return self.execute_command(name, *argv[2:])
  File "/Users/20002185/.conda/envs/brokeragevirtassistantportfolio/lib/python3.9/site-packages/smart_kit/management/app_manager.py", line 72, in execute_command
    return command.execute(*args, **kwargs)
  File "/Users/20002185/.conda/envs/brokeragevirtassistantportfolio/lib/python3.9/site-packages/smart_kit/management/app_manager.py", line 58, in execute
    return self._runner(self.app_config)
  File "/Users/20002185/.conda/envs/brokeragevirtassistantportfolio/lib/python3.9/site-packages/smart_kit/start_points/app.py", line 29, in run
    loop.run()
  File "/Users/20002185/.conda/envs/brokeragevirtassistantportfolio/lib/python3.9/site-packages/smart_kit/start_points/main_loop_kafka.py", line 126, in run
    loop.run_until_complete(self.general_coro())
  File "/Users/20002185/.conda/envs/brokeragevirtassistantportfolio/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/20002185/.conda/envs/brokeragevirtassistantportfolio/lib/python3.9/site-packages/smart_kit/start_points/main_loop_kafka.py", line 140, in general_coro
    await asyncio.gather(*tasks)
  File "/Users/20002185/.conda/envs/brokeragevirtassistantportfolio/lib/python3.9/site-packages/smart_kit/start_points/main_loop_kafka.py", line 170, in process_consumer
    await self.poll_kafka(kafka_key, self.queues)  # blocks while self.is_works
  File "/Users/20002185/.conda/envs/brokeragevirtassistantportfolio/lib/python3.9/site-packages/smart_kit/start_points/main_loop_kafka.py", line 276, in poll_kafka
    not_empty_queues_count = await self.put_to_queue(mq_message, self.do_incoming_handling, kwargs)
  File "/Users/20002185/.conda/envs/brokeragevirtassistantportfolio/lib/python3.9/site-packages/smart_kit/start_points/main_loop_kafka.py", line 287, in put_to_queue
    queue_index = int(hashlib.sha1(key).hexdigest(), 16) **% (len(self.queues) - 1)**
ZeroDivisionError: integer division or modulo by zero

**Comment by SyrexMinus** [comment]
Тикет https://jira.sberbank.ru/browse/DPNLPF-2171
